// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface DeleteCompteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Empty empty = 1;</code>
   * @return Whether the empty field is set.
   */
  boolean hasEmpty();
  /**
   * <code>.google.protobuf.Empty empty = 1;</code>
   * @return The empty.
   */
  com.google.protobuf.Empty getEmpty();
  /**
   * <code>.google.protobuf.Empty empty = 1;</code>
   */
  com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder();
}
